/*
 * Simple emlpoyee contract tracker api
 * This API allows management of client contracts and tracks history of employee contract assignments 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boxboat.simpletracker.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for History
 */
public class HistoryTest {
    private final History model = new History();

    /**
     * Model tests for History
     */
    @Test
    public void testHistory() {
        // TODO: test History
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'contractId'
     */
    @Test
    public void contractIdTest() {
        // TODO: test contractId
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'clientName'
     */
    @Test
    public void clientNameTest() {
        // TODO: test clientName
    }

    /**
     * Test the property 'employeeName'
     */
    @Test
    public void employeeNameTest() {
        // TODO: test employeeName
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

}
